// src/Utils/LocalStorage.jsx
export const employees = [
  {
    id: 1,
    firstName: "Wasi",
    email: "syedwasiakbar@gmail.com",
    password: "123",
    role: "employee",
    taskCounts: {
      newTask: 1,
      active: 1,
      completed: 1,
      failed: 1,
    },
    tasks: [
      {
        taskTitle: "Design Homepage",
        taskDescription: "Create a responsive homepage layout",
        taskDate: "2026-02-25",
        category: "Design",
        active: false,
        newTask: true,
        completed: false,
        failed: false,
      },
      {
        taskTitle: "Fix Navbar Bug",
        taskDescription: "Resolve the navigation bar overlapping issue",
        taskDate: "2026-02-23",
        category: "Development",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
      },
      {
        taskTitle: "Prepare Mockup",
        taskDescription: "Create mockups for new landing page",
        taskDate: "2026-02-28",
        category: "Design",
        active: false,
        newTask: false,
        completed: false,
        failed: true,
      },
      {
        taskTitle: "Active UI Work",
        taskDescription: "Working on active UI component",
        taskDate: "2026-02-28",
        category: "Design",
        active: true,
        newTask: false,
        completed: false,
        failed: false,
      },
    ],
  },
  {
    id: 2,
    firstName: "Ali",
    email: "ali.khan@example.com",
    password: "123",
    role: "employee",
    taskCounts: {
      newTask: 1,
      active: 1,
      completed: 1,
      failed: 0,
    },
    tasks: [
      {
        taskTitle: "Backend API Setup",
        taskDescription: "Setup REST APIs for project",
        taskDate: "2026-02-24",
        category: "Development",
        active: false,
        newTask: true,
        completed: false,
        failed: false,
      },
      {
        taskTitle: "Database Migration",
        taskDescription: "Migrate old database to new schema",
        taskDate: "2026-02-22",
        category: "Development",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
      },
      {
        taskTitle: "API Optimization",
        taskDescription: "Optimize slow API endpoints",
        taskDate: "2026-02-26",
        category: "Development",
        active: true,
        newTask: false,
        completed: false,
        failed: false,
      },
    ],
  },
  {
    id: 3,
    firstName: "Sara",
    email: "sara.ahmed@example.com",
    password: "123",
    role: "employee",
    taskCounts: {
      newTask: 1,
      active: 1,
      completed: 0,
      failed: 0,
    },
    tasks: [
      {
        taskTitle: "Test Login Feature",
        taskDescription: "Perform testing on login module",
        taskDate: "2026-02-23",
        category: "QA",
        active: false,
        newTask: true,
        completed: false,
        failed: false,
      },
      {
        taskTitle: "Bug Fixes",
        taskDescription: "Fix reported issues from QA",
        taskDate: "2026-02-25",
        category: "Development",
        active: true,
        newTask: false,
        completed: false,
        failed: false,
      },
    ],
  },
  {
    id: 4,
    firstName: "John",
    email: "john.doe@example.com",
    password: "123",
    role: "employee",
    taskCounts: {
      newTask: 1,
      active: 2,
      completed: 1,
      failed: 0,
    },
    tasks: [
      {
        taskTitle: "Update Documentation",
        taskDescription: "Update project documentation with new APIs",
        taskDate: "2026-02-27",
        category: "Documentation",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
      },
      {
        taskTitle: "Implement Search Feature",
        taskDescription: "Add search functionality to dashboard",
        taskDate: "2026-02-28",
        category: "Development",
        active: false,
        newTask: true,
        completed: false,
        failed: false,
      },
      {
        taskTitle: "Team Meeting",
        taskDescription: "Attend weekly sprint meeting",
        taskDate: "2026-02-22",
        category: "Meeting",
        active: true,
        newTask: false,
        completed: false,
        failed: false,
      },
      {
        taskTitle: "Code Review",
        taskDescription: "Review PRs from team members",
        taskDate: "2026-02-24",
        category: "Development",
        active: true,
        newTask: false,
        completed: false,
        failed: false,
      },
    ],
  },
  {
    id: 5,
    firstName: "Mina",
    email: "mina.shah@example.com",
    password: "123",
    role: "employee",
    taskCounts: {
      newTask: 1,
      active: 2,
      completed: 1,
      failed: 0,
    },
    tasks: [
      {
        taskTitle: "Create Landing Page",
        taskDescription: "Design and implement landing page UI",
        taskDate: "2026-02-26",
        category: "Design",
        active: false,
        newTask: true,
        completed: false,
        failed: false,
      },
      {
        taskTitle: "Optimize Images",
        taskDescription: "Compress images for faster load times",
        taskDate: "2026-02-24",
        category: "Development",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
      },
      {
        taskTitle: "Team Sync-up",
        taskDescription: "Discuss project updates with team",
        taskDate: "2026-02-23",
        category: "Meeting",
        active: true,
        newTask: false,
        completed: false,
        failed: false,
      },
      {
        taskTitle: "UI Polish",
        taskDescription: "Polish UI components for final review",
        taskDate: "2026-02-25",
        category: "Design",
        active: true,
        newTask: false,
        completed: false,
        failed: false,
      },
    ],
  },
];

export const admin = [
  {
    id: 6,
    email: "admin@me.com",
    password: "123",
    role: "admin",
  },
];

// Save employees & admin JSON to localStorage
export const setLocalstorage = () => {
  localStorage.setItem("employees", JSON.stringify(employees));
  localStorage.setItem("admin", JSON.stringify(admin));
};

// Retrieve employees and admin from localStorage
export const getLocalstorage = () => {
  const employees = JSON.parse(localStorage.getItem("employees"));
  const admin = JSON.parse(localStorage.getItem("admin"));
  return { employees, admin };
};